server:
  port: 8083

spring:
  application:
    name: webutils
  cloud:
    sentinel:
      transport:
        port: 8082
        dashboard: localhost:8081

test:
  strings:
    - "aaa"
    - "bbb"
    - "ccc"
  users:
    - user:
      name: 111
      password: 2222
    - user:
      name: aaaa
      password: bbbb
    - user:
      name: a1
      password: b1111
